name: deploy on ec2 1st time
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    - name: deploy on ec2 instances
    runs-on: ubuntu-latest
 
  steps:
    - name: checkout
    uses: actions/checkout@v2
    - name: Deploy to EC2  
    uses: easingthings/ssh-deploy@v1  
    with:  
      host: ${{ secrets.EC2_PUBLIC_IP }}  
      username: ec2-user  
      key: ${{ secrets.EC2_SSH_KEY }}  
      source: path/to/your/file.html  
      target: /var/www/html/file.html 
    
