name: deploy on ec2 1st time
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    - name: deploy on ec2 instances
    runs-on: ubuntu-latest
 
  steps:
    - name: checkout
    uses: actions/checkout@v2
    - name: Deploy to EC2  
    uses: easingthings/ssh-deploy@v1  
    env:
      REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}  
      USERNAME: ${{ secrets.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  
      TARGET: ${{ secrets.TARGET_DIR }}  
      
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }} 
        script: |
        sudo apt-get -y update
        sudo apt-get install apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2
        sudo cd home
        sudo mv * /var/www/html
        
